"""testing

Revision ID: 12c275d54c59
Revises: 9c370f37431f
Create Date: 2023-05-28 18:48:42.772711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c275d54c59'
down_revision = '9c370f37431f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
