"""Add game_user Association Table

Revision ID: 9c370f37431f
Revises: ba548d92416d
Create Date: 2023-05-28 18:44:35.131778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c370f37431f'
down_revision = 'ba548d92416d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
